-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 11:21:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema freitx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `person` ;

CREATE TABLE IF NOT EXISTS `person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `driverLicense` VARCHAR(50) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `imgsrc` VARCHAR(200) NOT NULL,
  `createAt` datetime NOT NULL,
  `updateAt` datetime NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `freight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freight` ;

CREATE TABLE IF NOT EXISTS `freight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idToday` VARCHAR(3) NOT NULL,
  `pickupMinDate` VARCHAR(24) NOT NULL,
  `pickupMaxDate` VARCHAR(24) NOT NULL,
  `deliverDate` VARCHAR(24) NOT NULL,
  `deliverImgsrc` VARCHAR(200) NOT NULL,
  `merchantId` INT NOT NULL,
  `driverId` INT NOT NULL,
  `fee` DECIMAL(10,2) NOT NULL,
  `barcode` VARCHAR(50) NOT NULL,
  `status` VARCHAR(10) NOT NULL, -- {PENDING, START, DELIVERY, COMPLETE, OVERDUE}
  `imgsrc` VARCHAR(200) NOT NULL,
  `createAt` datetime NOT NULL,
  `updateAt` datetime NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

CREATE TABLE IF NOT EXISTS `address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `freightId` INT NOT NULL,
  `type` VARCHAR(10) NOT NULL, -- {PICKUP, DROPOFF}
  `name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `line1` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  `createAt` datetime NOT NULL,
  `updateAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank` ;

CREATE TABLE IF NOT EXISTS `bank`  (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(50) NOT NULL,
  `routing` VARCHAR(50) NOT NULL,
  `name`    VARCHAR(50) NOT NULL,
  `personId` INT NOT NULL,
  `createAt` datetime NOT NULL,
  `updateAt` datetime NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `securityCode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `securityCode` ;

CREATE TABLE IF NOT EXISTS `securityCode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100),
  `code` VARCHAR(10) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `updateAt` datetime NOT NULL,
  `createAt` datetime NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
